### ISSUE TITLE
Problem with selecting country

### ISSUE THREAD

**Issue by chyrta** [ray1984/Telegram#1]
First of all, good job for the short period of time.
I had a problem in PhoneInputFragment where you have Cursor find(String country) function. I changed it to 'Belarus' and it works. Maybe you know about that issue.
Thanks.

**Comment by ray1984** [comment]
Вы выбрали Беларусь, а все работает? Удивительно! В чем проблема-то?

**Comment by chyrta** [comment]
Я не выбирал Беларусь, а лишь ввел уже в коде в методе find. Приложение вылетает на старте, если чисто довериться выбору последнего местоположения, если я все правильно понял. Пришлось самостоятельно добавить страну, чтобы ее нашло. Затем все работает.

**Comment by ray1984** [comment]
надо данные countries_insert править. Мне тоже пришлось Russian federation исправить на Russia, потому что в Location именно такое название отдает

**Comment by chyrta** [comment]
Ясно, думаю у вас все получится :)
